### PR TITLE
Update S3 client parameters to follow the lastest AWS SDK

### PR DESCRIPTION
**Pull request by combor**
### What

As there is no deps vendoring mechanism in this repo the latest AWS SDK is fetched when you do `go get -t .`. Unfortunately after that ginkgo fails with:

```
ginkgo -v -- -config=$CONFIG
Failed to compile benchmarkbbs:

# github.com/cloudfoundry/benchmarkbbs_test
./benchmark_bbs_suite_test.go:135: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to s3.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
./benchmark_bbs_suite_test.go:137: undefined: s3manager.UploadOptions
```
It seems that AWS SDK has changed a bit and now requires
client.ConfigProvider type as a first argument to s3.New method.

Also, s3manager.NewUploader was replaced with s3manager.NewUploaderWithClient that takes
*S3 as a argument.

### How to test

- check if code is sane
- get latest `aws-sdk-go` and run `ginkgo -v -- -config=$CONFIG`

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @combor. Have you tried running the benchmarkbbs test suite from the GOPATH provided by the [diego-release repository](https://github.com/cloudfoundry/diego-release)? That does vendor a specific version of the github.com/aws/aws-sdk-go repository via submodule.

Best,
Eric, CF Runtime Diego PM

**Comment by combor** [comment]
Hi @ematpl . Thanks for reply.  That makes sense to keep dependencies in sync for all the components  of diego-release. But what is the reason to keep bbs benchmarks in separate repository if it's unusable on it's own ?

**Comment by ematpl** [comment]
We can certainly improve the documentation to recommend that it be run from the version of the diego-release repository corresponding to the Diego deployment under test, to ensure that the dependencies are compatible. I've added https://www.pivotaltracker.com/story/show/137768741 to address that.

I think it's a bit strong to say that this repository is "unusable" independently simply because it isn't directly go-gettable. Keeping the test suite code in a separate Git repository under `code.cloudfoundry.org` also produces a clearer organizational structure for the code and the Diego BOSH release than the alternatives (compare the more confusing import paths for [confab](https://github.com/cloudfoundry-incubator/consul-release/blob/master/src/confab/confab/main.go) in [consul-release](https://github.com/cloudfoundry-incubator/consul-release), or the non-importable [loggregator source](https://github.com/cloudfoundry/loggregator/tree/develop/src) in the [loggregator BOSH release](https://github.com/cloudfoundry/loggregator)).

If Golang's support for semantic versioning of package dependencies improves (and the Golang community is now finally [starting to address those problems seriously](https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/)) then it may well be possible to make this repository directly consumable outside of the set of submodule-locked dependencies in diego-release.

Thanks,
Eric

**Comment by ematpl** [comment]
Closing this out, as https://www.pivotaltracker.com/story/show/137768741 is finished in [Diego v1.14.1](https://github.com/cloudfoundry/diego-release/releases/tag/v1.14.1).

**Pull request closed without merging**
